### ISSUE TITLE
initialising weights not with inverse of mean std

### ISSUE THREAD

**Issue by florianmahner** [LukasMut/VICE#10]
https://github.com/LukasMut/VICE/blob/99f00289c724875cfe8d17283dc7760fa421509e/model/vice.py#L108

should this not be `eps = -(self.mu.mu.weight.data.std().log() ** -1.0).exp()` instead?

**Comment by LukasMut** [comment]
No. Why should it be like this? $\mathbb{V}[X]$ is intended to be small at the beginning of the optimization process. We assume that there is no variance (we have no prior knowledge about it) and start with the mean $\mathbb{E}[X]$. This acts like a dirac delta function on the mode of the distribution (which is a random Gaussian variable). Note that the variance cannot be initialized with all zeros which is why it's a number close to zero. Over time the model figures out the variance across objects and dimensions. Of course, this could have been a value other than ``-(self.mu.mu.weight.data.std().log() * -1.0).exp()`` but that's a design choice.
